# Multi-OS is in invite-only beta on Travis right now
# Ref: http://docs.travis-ci.com/user/multi-os/
#
# os:
#   - linux
#   - osx

# matrix:
#   allow_failures:
#     - os: osx

# Use containers
sudo: false

# Without root, we have to get CI to install apt pkgs for us
# These must match with the Prepare target in scripts/0-setup.sh
addons:
  apt:
    packages:
      - build-essential
      - ca-certificates
      - gfortran
      - libatlas-base-dev
      - libatlas3gf-base
      - libgmp10
      - liblapack-dev
      - liblapack3gf
      - libmpfr4
      - libpcre3-dev
      - libssl-dev
      - python-dev
      - python-pip
      - python-virtualenv
      - uuid-runtime
      # Travis is still on 12.04 and can't make SSL connections
      # https://github.com/travis-ci/travis-ci/issues/4757
      # http://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
      - openssl

language: python
python:
  - "2.7"

# Explicitly disable heuristic cleverness
install: true

script:
  - ./live.sh ci
