# Multi-OS is in invite-only beta on Travis right now
# Ref: http://docs.travis-ci.com/user/multi-os/
#
# os:
#   - linux
#   - osx

# matrix:
#   allow_failures:
#     - os: osx

# Use containers
sudo: false

# Without root, we have to get CI to install apt pkgs for us
addons:
  apt:
    packages:
      - build-essential
      - python-dev
      # Python CI provider allegedly already has these
      # - python-virtualenv
      # - python-pip

language: python
python:
  - "2.7"

# Explicitly disable heuristic cleverness
install: true

script:
  - ./live.sh ci
